// <auto-generated />
using System;
using ClimaWatch.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClimaWatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClimaWatchDbContext))]
    [Migration("20260617165148_AddWeatherAlertsAndNotifications")]
    partial class AddWeatherAlertsAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClimaWatch.Infrastructure.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("WeatherAlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("weather_alert_id");

                    b.HasKey("Id");

                    b.HasIndex("WeatherAlertId", "Channel")
                        .IsUnique();

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("alert_type");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at_utc");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<Guid>("WeatherCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("weather_check_id");

                    b.Property<Guid>("WeatherSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("weather_snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("WeatherCheckId");

                    b.HasIndex("WeatherSnapshotId");

                    b.ToTable("weather_alerts", (string)null);
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("city");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error_message");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("weather_checks", (string)null);
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("ApparentTemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("apparent_temperature_c");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("location_name");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at_utc");

                    b.Property<double>("PrecipitationMm")
                        .HasColumnType("double precision")
                        .HasColumnName("precipitation_mm");

                    b.Property<string>("RawPayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload_json");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_c");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<Guid>("WeatherCheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("weather_check_id");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("integer")
                        .HasColumnName("weather_code");

                    b.Property<double>("WindSpeedKmh")
                        .HasColumnType("double precision")
                        .HasColumnName("wind_speed_kmh");

                    b.HasKey("Id");

                    b.HasIndex("WeatherCheckId")
                        .IsUnique();

                    b.ToTable("weather_snapshots", (string)null);
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.Notification", b =>
                {
                    b.HasOne("ClimaWatch.Infrastructure.WeatherAlert", "WeatherAlert")
                        .WithMany("Notifications")
                        .HasForeignKey("WeatherAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherAlert");
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherAlert", b =>
                {
                    b.HasOne("ClimaWatch.Infrastructure.WeatherCheck", "WeatherCheck")
                        .WithMany()
                        .HasForeignKey("WeatherCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimaWatch.Infrastructure.WeatherSnapshot", "WeatherSnapshot")
                        .WithMany()
                        .HasForeignKey("WeatherSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherCheck");

                    b.Navigation("WeatherSnapshot");
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherSnapshot", b =>
                {
                    b.HasOne("ClimaWatch.Infrastructure.WeatherCheck", "WeatherCheck")
                        .WithOne()
                        .HasForeignKey("ClimaWatch.Infrastructure.WeatherSnapshot", "WeatherCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherCheck");
                });

            modelBuilder.Entity("ClimaWatch.Infrastructure.WeatherAlert", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
